/**
 * Every document the tool writes into a repo, as code — one source for what
 * `init` scaffolds, what `session template <name>` prints, and what the
 * session-log reference describes. A template that lived as a markdown file
 * beside a prose copy of itself drifted; here the tool is the copy.
 */
import { template } from "./session-lib";

export const SESSIONS_INDEX_START = "<!-- sessions:start -->";
export const SESSIONS_INDEX_END = "<!-- sessions:end -->";

/** The session file `new` writes, shown with placeholder prose instead of `_(fill in)_`. */
export function sessionFileTemplate(): string {
  return `# [YYYY-MM-DD HH:MM] · [Title of the session]

- Goal: [what this session set out to do]
- Status: open
- Plan: [PLAN-NNN · part N, or —]
- Outcome: [what it actually delivered — releases, merged PRs; written when it closes]
- Open at end: [the handoff — what the next conversation picks up first, what is unverified]

## Narrative

[What was asked, decided, tried and abandoned, verified and how; cite entries by sha]

## Changes (one entry per commit, in order)

### [YYYY-MM-DD] · [type(scope): subject] · [sha]

- Summary: [what this change does as a whole, one or two lines]
- Why: [the problem or request that caused it, naming who asked]
- Also: [sha] — [what that fix-up fixed]                (only when a fix-up is vouched for)
- Files:
  - \`[path/to/file]\` (+[a]/−[d]) — [what changed in this file]
- Notes: [verified how; unverified what; follow-ups; a decision made on the spot]

> **Released [vX.Y.Z]** — tag on this commit.          (only under a release commit's entry)
`;
}

/** `docs/sessions/README.md`: purpose, the index the tool regenerates, the file template. */
export function sessionsReadme(): string {
  return `# Sessions — what has been done, session by session

One file per **session** — a bounded stream of work toward one Goal, \`open\` until \`closed\`, which
may span any number of conversations. A session usually serves one **part** of a plan in
\`../plan/\`, and that part's status line names the session, so a plan is enough to find the story
of its work. Together these files are the append-only record of every change that reached \`main\`
— for each commit a Summary, the Why, and a note per touched file — **plus** the narrative a
commit log cannot hold: what was asked, tried, abandoned, verified. A new conversation reads them
to pick up exactly where the last one stopped.

The procedure that reads and writes them is the \`/session\` skill (the \`sessions\` plugin):
\`/session start [PLAN-NNN]\` or \`/session continue [PLAN-NNN]\` at the beginning of a
conversation, \`/session entry\` right after every commit, \`/session end\` before leaving,
\`/session close\` when the Goal is done. The rules — what an entry holds, which commits get none,
what is never rewritten — are the skill's, so they live with it rather than being copied here; the
tool behind it regenerates the index below.

## Index (newest first — regenerated by the session tool)

${SESSIONS_INDEX_START}
${SESSIONS_INDEX_END}

## Session file template

\`\`\`markdown
${sessionFileTemplate().trimEnd()}
\`\`\`
`;
}

/** `docs/plan/README.md`: the PRD and plan shapes with the per-part status line. */
export function planReadme(): string {
  return `# Plan — what we are building and how

Two kinds of document: the **PRD** (\`PRD-NNN-<product>.md\` — what the product is, for whom, the
promise, the requirements, boundaries, success criteria; the single source for *what* and *why*,
kept current) and **feature plans** (\`PLAN-NNN-<feature>.md\`, one per piece of work larger than a
small fix: overview, the decisions it relies on, the parts in order, risks, open questions).

**A plan is the way in.** "Work on PLAN-NNN" is enough for a new conversation: each **part**
carries a status line — \`planned\`, \`in progress (session SES-NNN)\` or
\`done (session SES-NNN, sha)\` — so the plan says where the work stands and which session in
\`../sessions/\` holds the story of each part, and the session's \`Plan:\` line points back. The PRD's
\`## Plans\` table lists every plan implementing it, so PRD → plan → part → session is one walk.
The \`/session\` skill (the \`sessions\` plugin) writes those status lines and ticks; progress is read
from the session entries, never tracked twice.

## Index

| Doc | What | Status |
| --- | --- | --- |

## Rules

- **PRD first, then plan, then parts, then code** for anything non-trivial. A change to *what* we
  build updates the PRD in the same PR; a change to *how* updates the feature plan.
- **Decisions with alternatives** are ADRs in the decisions directory, linked from here — a plan
  cites decisions, it does not restate them. **Facts** come from the analysis directory.
- **One session per part.** A second conversation on the same part joins its session.
- A finished plan is not deleted: its top status becomes
  \`done — shipped in vX.Y.Z (session SES-NNN)\` and the PRD's Plans row says the same.

## Templates

### PRD

\`\`\`markdown
# PRD: <product>

> Status: current as of vX.Y.Z · YYYY-MM-DD · last change: session entry \`<sha>\`

## Objective — what, why, for whom; what success looks like
## The promise — the user-visible contract
## Requirements — numbered, testable
## Tech stack · Project structure · Code style · Testing strategy
## Boundaries — Always / Ask first / Never
## Success criteria — specific, testable
## Non-goals
## Open questions

## Plans

| Plan | Implements | Status |
| --- | --- | --- |
| PLAN-001-<feature>.md | requirements 3, 4 | in progress — part 2 (session SES-NNN) |
\`\`\`

### Feature plan

\`\`\`markdown
# Plan: <feature>

> Status: planned | in progress | done — shipped in vX.Y.Z (session SES-NNN) · owner · YYYY-MM-DD

## Overview
One paragraph: what and why (link the PRD requirement).

## Decisions it relies on
- ADR-NNN … (link); new decisions needed → write the ADR first.

## Parts

### Part 1: <title>

> Status: done (session SES-004, \`a1b2c3d\`)

- [x] Task 1: <title> — acceptance criteria; verification — \`a1b2c3d\`
- [x] Checkpoint: tests green; manual check … — \`a1b2c3d\`

### Part 2: <title>

> Status: in progress (session SES-006)

- [x] Task 1: … — \`e4f5a6b\`
- [ ] Task 2: … — acceptance criteria; verification; files

### Part 3: <title>

> Status: planned

- [ ] Task 1: …

## Risks and mitigations
| Risk | Impact | Mitigation |

## Open questions
\`\`\`
`;
}

export const CONTEXT_SECTION_HEADING = "## The session log (the docs system)";

/** The glossary section `init` appends to (or creates) `CONTEXT.md`. */
export function contextSection(): string {
  return `${CONTEXT_SECTION_HEADING}

**Session log**:
The \`docs/sessions/\` files together: the append-only record of every change that reached \`main\`
and the narrative around it — what a conversation reads to rehydrate.
_Avoid_: ledger, history, changelog (that is the generated one)

**Session**:
A bounded stream of work toward one Goal, recorded in one \`docs/sessions/SES-NNN\` file; **open**
from the moment it is opened until it is **closed** with its Outcome written. It may span any
number of conversations and may serve a plan part (its \`Plan:\` line).
_Avoid_: conversation (for this), sitting, chat, the newest file (as the definition of current)

**Conversation**:
One agent context or one human sitting. A participant in a session: it joins the open session
whose Goal is its work, or opens one, before its first commit; a conversation that changes nothing
needs none.
_Avoid_: session (for this)

**Open** / **Closed** (session status):
Open — work toward the Goal may still land; the tool appends entries and gates it. Closed — the
Goal is done or abandoned, the Outcome says which; nothing is appended to it again.
_Avoid_: current (as the status word), active, done (for the status), finished

**Join** / **Open** / **Leave** / **Close** (a conversation's moves):
Join — take an open session as yours because you will record entries into it and its Goal is your
work; never a session another conversation owns. Open — start a new session for new work. Leave —
stop for now with the log complete and a handoff written; the session stays open. Close — the
Goal is done: Outcome written, status flipped to closed.
_Avoid_: end (for close), finish, resume (for join), create (for open)

**Plan part**:
One \`### Part N\` of a plan in \`docs/plan/\`, with its own status line — \`planned\`, \`in progress
(session SES-NNN)\` or \`done (session SES-NNN, sha)\` — the pointer a new conversation follows from
the plan to the session that holds its story. One session per part.
_Avoid_: phase (as the heading word), step, milestone, ticket

**Handoff**:
The \`Open at end\` line of an open session: what the next conversation picks up first and what is
unverified, written when a conversation leaves.
_Avoid_: notes, todo, next steps (as the field name)

**Gate**:
\`session check\`: exit 0 only when every commit on the branch is accounted for and your session has
no placeholder the gate counts. Its exit status is the verdict; nothing is piped after it.
_Avoid_: check (as the noun), lint, validation

**Entry**:
The block a change worth reading about gets in a session file — Summary, Why, one line per
touched file, Notes — written by \`/session entry\` right after the commit. The session log holds
value only: a fix-up commit gets no entry and is vouched for by its parent's \`Also:\` line; a commit
with nothing to record says so itself (\`Session-entry: none\`) and gets none.
_Avoid_: log entry, note, update, record (as the noun), commit (as the unit — a commit is git's)

**Record** (verb):
To write the entry and update everything the commit made stale, in the same step; the practice
the docs system depends on.
_Avoid_: update, log, document (as the verb for this)
`;
}

export const TEMPLATES = {
  session: sessionFileTemplate,
  "sessions-readme": sessionsReadme,
  "plan-readme": planReadme,
  context: contextSection,
} as const;
export type TemplateName = keyof typeof TEMPLATES;
