/**
 * Every document the tool writes into a repo, as code — one source for what
 * `init` scaffolds, what `session template <name>` prints, and what the
 * session-log reference describes. A template that lived as a markdown file
 * beside a prose copy of itself drifted; here the tool is the copy.
 */
import { template } from "./session-lib";

export const SESSIONS_INDEX_START = "<!-- sessions:start -->";
export const SESSIONS_INDEX_END = "<!-- sessions:end -->";

/** The session file `new` writes, shown with placeholder prose instead of `_(fill in)_`. */
export function sessionFileTemplate(): string {
  return `# [YYYY-MM-DD HH:MM] · [Title of the session]

- Goal: [what this session set out to do]
- Status: in progress
- Plan: [PLAN-NNN · part N, or —]
- Outcome: [what it actually delivered — releases, merged PRs; written when it closes]

## Narrative

[What was asked, decided, tried and abandoned, verified and how; cite entries by sha]

## Changes (one entry per commit, in order)

### [YYYY-MM-DD] · [type(scope): subject] · [sha]

- Summary: [what this change does as a whole, one or two lines]
- Why: [the problem or request that caused it, naming who asked]
- Also: [sha] — [what that fix-up fixed]                (only when a fix-up is vouched for)
- Files:
  - \`[path/to/file]\` (+[a]/−[d]) — [what changed in this file]
- Notes: [verified how; unverified what; follow-ups; a decision made on the spot]

> **Released [vX.Y.Z]** — tag on this commit.          (only under a release commit's entry)
`;
}

/** `docs/sessions/README.md`: purpose, the index the tool regenerates, the file template. */
export function sessionsReadme(): string {
  return `# Sessions — what has been done, session by session

One file per **session** — a bounded stream of work toward one Goal, \`in progress\` until \`done\`, which
may span any number of conversations. A session usually serves one **part** of a plan in
\`../plan/\`, and that part's status line names the session, so a plan is enough to find the story
of its work. Together these files are the append-only record of every change that reached \`main\`
— for each commit a Summary, the Why, and a note per touched file — **plus** the narrative a
commit log cannot hold: what was asked, tried, abandoned, verified. A new conversation reads them
to pick up exactly where the last one stopped: the plan says what is next, the entries say what
was verified and what was not.

The procedure that writes them is the \`session\` skill (the \`sessions\` plugin), three acts:
\`start\` creates a session from a description when a stream of work begins, \`log\` records a
commit right after it lands, \`close\` finishes a session whose Goal is done. Where a plan stands
and what comes next is \`/plan PLAN-NNN\`'s to say. The rules — what an entry holds, which commits
get none, what is never rewritten — are the skill's, so they live with it rather than being copied
here; the tool behind it regenerates the index below.

## Index (newest first — regenerated by the session tool)

${SESSIONS_INDEX_START}
${SESSIONS_INDEX_END}

## Session file template

\`\`\`markdown
${sessionFileTemplate().trimEnd()}
\`\`\`
`;
}

export const CONTEXT_SECTION_HEADING = "## The session log (the docs system)";

/** The glossary section `init` appends to (or creates) `CONTEXT.md`. */
export function contextSection(): string {
  return `${CONTEXT_SECTION_HEADING}

**Session log**:
The \`docs/sessions/\` files together: the append-only record of every change that reached \`main\`
and the narrative around it — what a conversation reads to rehydrate.
_Avoid_: ledger, history, changelog (that is the generated one)

**Session**:
A bounded stream of work toward one Goal, recorded in one \`docs/sessions/SES-NNN\` file;
\`in progress\` from \`start\` until \`close\` writes \`done\` with its Outcome. It may span any
number of conversations and may serve a plan part (its \`Plan:\` line).
_Avoid_: conversation (for this), sitting, chat, the newest file (as the definition of current)

**Conversation**:
One agent context or one human sitting. A participant in a session: it names the session in
progress it logs into, or starts one, before its first commit; a conversation that changes nothing
needs none.
_Avoid_: session (for this)

**Status** (one vocabulary for session, plan and plan part):
A session is \`in progress\` from \`session new\` until \`session close\` writes \`done\` — the Outcome says
whether the Goal was met or abandoned; nothing is appended to a done session. A plan part is
\`planned\`, \`in progress (session SES-NNN)\` or \`done (session SES-NNN, sha)\`; a plan is \`planned\`,
\`in progress\` or \`done\`. Tickets and ADRs carry their own words (triage roles; Accepted / Superseded).
_Avoid_: open, closed (the pre-ADR-024 session words, still read), active, current, finished, complete (as a status)

**Start** / **Log** / **Close** (the three acts of the session skill):
Start — a new session from a description: its Goal, its \`Plan:\` line, its plan part marked in
progress. Log — a commit's entry into a session in progress, with everything the change made
stale. Close — the Goal is done: Outcome written, status \`done\`, the plan part done. The act is
inferred from the arguments; close is always named. A conversation that stops does nothing.
_Avoid_: join, open, leave, end, add, record, entry (as the act name)

**Plan part**:
One \`### Part N\` of a plan in \`docs/plan/\`, with its own status line — \`planned\`, \`in progress
(session SES-NNN)\` or \`done (session SES-NNN, sha)\` — the pointer a new conversation follows from
the plan to the session that holds its story. One session per part.
_Avoid_: phase (as the heading word), step, milestone, ticket

**Gate**:
\`session check\`: exit 0 only when every commit on the branch is accounted for and your session has
no placeholder the gate counts. Its exit status is the verdict; nothing is piped after it.
_Avoid_: check (as the noun), lint, validation

**Entry**:
The block a change worth reading about gets in a session file — Summary, Why, one line per
touched file, Notes — written by the \`log\` act right after the commit. The session log holds
value only: a fix-up commit gets no entry and is vouched for by its parent's \`Also:\` line; a commit
with nothing to record says so itself (\`Session-entry: none\`) and gets none.
_Avoid_: log entry, note, update, record (as the noun), commit (as the unit — a commit is git's)

**Record** (verb):
To write the entry and update everything the commit made stale, in the same step; the practice
the docs system depends on.
_Avoid_: update, log, document (as the verb for this)
`;
}

export const TEMPLATES = {
  session: sessionFileTemplate,
  "sessions-readme": sessionsReadme,
  context: contextSection,
} as const;
export type TemplateName = keyof typeof TEMPLATES;
