#!/usr/bin/env bun
// concept-index.ts — derive docs/analysis/concepts/<pkg>/_index.md from the concept cards (METHOD §5 Phase 2; D-023).
// Never hand-written: the index is a view of the cards, regenerated at §7 step 7 like the manifests' Checked column.
//
//   bun scripts/synthesis/concept-index.ts            write _index.md for every package that has concept cards
//   bun scripts/synthesis/concept-index.ts --check    exit 1 if any _index.md is not what the cards produce now
//
// One line per card — `- [name](./slug.md) — kind` — grouped by the card's `package_phase` (the package's own phase
// name, prefixed; `none` / `cross-phase` / missing → "Cross-phase and unassigned"), groups and lines sorted.
import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { PKGS, parseFrontmatter } from "./_lib";

const check = process.argv.includes("--check");
let bad = 0, written = 0;
for (const pkg of PKGS) {
  const dir = `docs/analysis/concepts/${pkg}`;
  if (!existsSync(dir)) continue;
  const cards = readdirSync(dir).filter(f => f.endsWith(".md") && !f.startsWith("_")).sort();
  if (!cards.length) continue;
  const groups = new Map<string, string[]>();
  for (const f of cards) {
    const { fm } = parseFrontmatter(readFileSync(`${dir}/${f}`, "utf8"));
    const slug = f.replace(/\.md$/, "");
    const phase = String(fm.package_phase ?? "").trim();
    const g = !phase || /^(none|cross-phase)$/i.test(phase) ? "Cross-phase and unassigned" : phase;
    (groups.get(g) ?? groups.set(g, []).get(g)!).push(`- [${String(fm.name ?? slug).replace(/[\[\]]/g, "")}](./${slug}.md) — ${fm.kind ?? "?"}`);
  }
  const out = [`# Concept cards — ${pkg}`, "", `${cards.length} cards. Generated by \`scripts/synthesis/concept-index.ts\` from the cards' frontmatter; do not edit.`, "",
    ...[...groups.keys()].sort().flatMap(g => [`## ${g}`, "", ...groups.get(g)!.sort(), ""])].join("\n");
  const target = `${dir}/_index.md`;
  const cur = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (check) { if (cur !== out) { console.log(`concept-index: ${target} is stale (${cards.length} cards)`); bad++; } else console.log(`concept-index: ${target} matches (${cards.length} cards)`); continue; }
  if (cur !== out) { writeFileSync(target, out); written++; }
  console.log(`concept-index: ${target} — ${cards.length} cards in ${groups.size} group(s)${cur === out ? " (unchanged)" : ""}`);
}
if (check) process.exit(bad ? 1 : 0);
if (!written) console.log("concept-index: nothing to write");
