#!/usr/bin/env bun
// dedupe.ts — duplication ledger for one source package (pure Bun, no deps).
//
//   bun scripts/synthesis/dedupe.ts <pkg> <repo-root> [manifest.md] > docs/analysis/manifest/<pkg>-duplicates.md
//
// Reads the file list (from the manifest if given, else `git ls-files`), hashes every
// file, and writes a ledger with three sections:
//   1. EXACT   — byte-identical groups. One canonical path per group + aliases.
//   2. VARIANT — same name under different roots, content differs but ≥ THRESHOLD of
//                distinct lines are shared. Emits the full unified diff so the
//                divergence is evaluated in full, never skimmed.
//   3. STATS   — how many reads the ledger saves.
// The ledger is an INPUT to inventory, never a filter that removes files from the
// manifest: every path stays a manifest row; rows in an EXACT group point at one card.
import { readFileSync, existsSync, statSync } from "fs";
import { execSync, spawnSync } from "child_process";
import { createHash } from "crypto";

const [pkg, root, manifest] = process.argv.slice(2);
if (!pkg || !root) { console.error("usage: dedupe.ts <pkg> <repo-root> [manifest.md]"); process.exit(2); }
const THRESHOLD = Number(process.env.DEDUPE_THRESHOLD ?? "0.6");
const MIN_BYTES = 200;

let paths: string[];
if (manifest) {
  paths = readFileSync(manifest, "utf8").split("\n")
    .filter(l => l.startsWith("| ") && !l.startsWith("| Path") && !/^\|\s*-+/.test(l))
    .map(l => (l.split("|")[1] ?? "").trim());
} else {
  paths = execSync("git ls-files", { cwd: root, encoding: "utf8" }).trim().split("\n");
}

type F = { path: string; hash: string; bytes: number; lines: string[]; isLink: boolean };
const files: F[] = [];
for (const p of paths) {
  const full = `${root}/${p}`;
  if (!existsSync(full) || !statSync(full).isFile()) continue;
  const buf = readFileSync(full);
  let isLink = false;
  try { isLink = require("fs").lstatSync(full).isSymbolicLink(); } catch {}
  files.push({ path: p, hash: createHash("sha256").update(buf).digest("hex").slice(0, 16), bytes: buf.length, lines: buf.toString("utf8").split("\n"), isLink });
}
const sha = (() => { try { return execSync("git rev-parse HEAD", { cwd: root, encoding: "utf8" }).trim(); } catch { return "unknown"; } })();

// ---- 1. exact groups
const byHash = new Map<string, F[]>();
for (const f of files) (byHash.get(f.hash) ?? byHash.set(f.hash, []).get(f.hash)!).push(f);
const groups = [...byHash.values()].filter(g => g.length > 1)
  .map(g => g.sort((a, b) => Number(a.isLink) - Number(b.isLink) || a.path.length - b.path.length || a.path.localeCompare(b.path)))
  .sort((a, b) => b[0]!.bytes * (b.length - 1) - a[0]!.bytes * (a.length - 1));

// ---- 2. variants: same "name key" (basename, or parent/basename for SKILL.md-style files)
function nameKey(p: string) {
  const s = p.split("/"); const b = (s[s.length - 1] ?? "").replace(/\.agent\.md$/, ".md").replace(/\.shared\.md$/, ".md");
  return /^(SKILL|README|CLAUDE|AGENTS|GEMINI|index)\.md$/i.test(b) ? s.slice(-2).join("/") : b;
}
const byKey = new Map<string, F[]>();
for (const f of files) (byKey.get(nameKey(f.path)) ?? byKey.set(nameKey(f.path), []).get(nameKey(f.path))!).push(f);
function shared(a: F, b: F) {
  const sa = new Set(a.lines), sb = new Set(b.lines); let c = 0;
  for (const l of sa) if (sb.has(l)) c++;
  return c / Math.max(sa.size, sb.size, 1);
}
type V = { a: F; b: F; ratio: number };
const variants: V[] = [];
for (const g of byKey.values()) {
  if (g.length < 2) continue;
  for (let i = 0; i < g.length; i++) for (let j = i + 1; j < g.length; j++) {
    const a = g[i], b = g[j]; if (!a || !b) continue;
    if (a.hash === b.hash || a.bytes < MIN_BYTES || b.bytes < MIN_BYTES) continue;
    const r = shared(a, b);
    if (r >= THRESHOLD) variants.push({ a, b, ratio: r });
  }
}
variants.sort((x, y) => y.ratio - x.ratio);

function udiff(a: F, b: F) {
  const r = spawnSync("diff", ["-u", "--label", a.path, "--label", b.path, `${root}/${a.path}`, `${root}/${b.path}`], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  return (r.stdout || "").replace(/```/g, "` ` `");
}

// ---- output
const out: string[] = [];
out.push(`# Duplication ledger — ${pkg}`, ``,
  `- source: \`${root}\` @ \`${sha}\``,
  `- scope: ${manifest ? `manifest \`${manifest}\` (${paths.length} rows)` : `\`git ls-files\` (${paths.length} files)`}`,
  `- files hashed: ${files.length}; distinct contents: ${byHash.size}`,
  `- generated by \`scripts/synthesis/dedupe.ts\` (threshold ${THRESHOLD}); regenerate, never hand-edit`, ``);

out.push(`## 1. EXACT — byte-identical groups (${groups.length} groups, ${groups.reduce((n, g) => n + g.length - 1, 0)} redundant files, ${(groups.reduce((n, g) => n + (g.length - 1) * g[0]!.bytes, 0) / 1024).toFixed(0)} KB)`, ``,
  `Rule: one concept card per group, written against the **canonical** path (first column); every alias row in the manifest is checked off by that card and cites the canonical \`path:line\` plus \`(= alias)\`. Symlinks are marked.`, ``,
  `| # | canonical | aliases | bytes | hash |`, `|---|---|---|---|---|`);
groups.forEach((g, i) => out.push(`| ${i + 1} | \`${g[0]!.path}\` | ${g.slice(1).map(f => "`" + f.path + "`" + (f.isLink ? " (symlink)" : "")).join("<br>")} | ${g[0]!.bytes} | \`${g[0]!.hash}\` |`));
if (!groups.length) out.push(`| — | none | | | |`);
out.push(``);

out.push(`## 2. VARIANT — same name, different content, ≥${Math.round(THRESHOLD * 100)}% shared lines (${variants.length} pairs)`, ``,
  `Rule: the pair is inventoried as ONE concept card plus a **divergence card** that quotes every changed hunk verbatim and classifies it (\`harness-substitution\` · \`content\` · \`generated-from\`). Nothing in the diff is skipped; the saving is the shared body, not the delta.`, ``);
if (!variants.length) out.push(`none`, ``);
variants.forEach((v, i) => {
  out.push(`### V${i + 1} · ${(v.ratio * 100).toFixed(0)}% shared · \`${v.a.path}\` ↔ \`${v.b.path}\``, ``, "```diff", udiff(v.a, v.b).trimEnd(), "```", ``);
});

const redundantBytes = groups.reduce((n, g) => n + (g.length - 1) * g[0]!.bytes, 0);
const variantSavedBytes = variants.reduce((n, v) => n + Math.min(v.a.bytes, v.b.bytes) * v.ratio, 0);
const totalBytes = files.reduce((n, f) => n + f.bytes, 0);
out.push(`## 3. STATS`, ``,
  `| metric | value |`, `|---|---|`,
  `| bytes in scope | ${totalBytes} |`,
  `| bytes not re-read thanks to EXACT groups | ${redundantBytes} (${(100 * redundantBytes / Math.max(totalBytes, 1)).toFixed(1)}%) |`,
  `| bytes approx. shared inside VARIANT pairs | ${Math.round(variantSavedBytes)} (${(100 * variantSavedBytes / Math.max(totalBytes, 1)).toFixed(1)}%) |`, ``);
console.log(out.join("\n"));
